#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright 2018 Google LLC
# Copyright 2026 Red Hat
#
# FS QA Test generic/2002
#
# Check that fsverity works on files with extent hints
#
. ./common/preamble
_begin_fstest auto quick verity

# Override the default cleanup function.
_cleanup()
{
	cd /
	_restore_fsverity_signatures
	rm -f $tmp.*
}

# Import common functions.
. ./common/filter
. ./common/verity

_require_scratch_verity
_disable_fsverity_signatures

_scratch_mkfs_verity &>> $seqres.full
_scratch_mount

fsv_orig_file=$SCRATCH_MNT/dir/file
fsv_file=$SCRATCH_MNT/dir/file.fsv

filter_output()
{
	_filter_bash | _filter_scratch
}

verify_data_readable()
{
	local file=$1

	md5sum $file > /dev/null
}


_fsv_scratch_begin_subtest "verity file has correct contents and size"
mkdir -p "$SCRATCH_MNT/dir"
$XFS_IO_PROG -c "chattr +X" -c "extsize 1m" "$SCRATCH_MNT/dir" >> $seqres.full
head -c 100000 /dev/urandom > $fsv_orig_file
cp $fsv_orig_file $fsv_file
_fsv_enable $fsv_file >> $seqres.full
cmp $fsv_file $fsv_orig_file
_get_filesize $fsv_file
_scratch_cycle_mount
cmp $fsv_file $fsv_orig_file
_get_filesize $fsv_file

_fsv_scratch_begin_subtest "Trying to measure non-verity file fails with ENODATA"
mkdir -p "$SCRATCH_MNT/dir"
$XFS_IO_PROG -c "chattr +X" -c "extsize 1m" "$SCRATCH_MNT/dir" >> $seqres.full
echo foo > $fsv_file
_fsv_measure $fsv_file |& filter_output
verify_data_readable $fsv_file

# Test files <= 1 block in size.  These are a bit of a special case since there
# are no hash blocks; the root hash is calculated directly over the data block.
_fsv_scratch_begin_subtest "verity on small files"
mkdir -p "$SCRATCH_MNT/dir"
$XFS_IO_PROG -c "chattr +X" -c "extsize 1m" "$SCRATCH_MNT/dir" >> $seqres.full
for size in 1 $((FSV_BLOCK_SIZE - 1)) $FSV_BLOCK_SIZE; do
	head -c $size /dev/urandom > $fsv_orig_file
	cp $fsv_orig_file $fsv_file
	_fsv_enable $fsv_file
	cmp $fsv_orig_file $fsv_file && echo "Files matched"
	rm -f $fsv_file
done

_fsv_scratch_begin_subtest "verity on 100MB file (multiple levels in hash tree)"
mkdir -p "$SCRATCH_MNT/dir"
$XFS_IO_PROG -c "chattr +X" -c "extsize 1m" "$SCRATCH_MNT/dir" >> $seqres.full
head -c 100000000 /dev/urandom > $fsv_orig_file
cp $fsv_orig_file $fsv_file
_fsv_enable $fsv_file
cmp $fsv_orig_file $fsv_file && echo "Files matched"

_fsv_scratch_begin_subtest "verity on sparse file"
mkdir -p "$SCRATCH_MNT/dir"
$XFS_IO_PROG -c "chattr +X" -c "extsize 1m" "$SCRATCH_MNT/dir" >> $seqres.full
dd if=/dev/zero of=$fsv_orig_file bs=1 count=1 seek=1000000 status=none
cp $fsv_orig_file $fsv_file
_fsv_enable $fsv_file
cmp $fsv_orig_file $fsv_file && echo "Files matched"

# success, all done
status=0
exit
