#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright 2018 Google LLC
# Copyright 2026 Red Hat
#
# FS QA Test xfs/2003
#
# Check that fsverity works on reflinks
#
. ./common/preamble
_begin_fstest auto quick verity

# Override the default cleanup function.
_cleanup()
{
	cd /
	_restore_fsverity_signatures
	rm -f $tmp.*
}

# Import common functions.
. ./common/filter
. ./common/verity
. ./common/reflink

_require_scratch_verity
_require_scratch_reflink
_require_cp_reflink
_disable_fsverity_signatures

_scratch_mkfs_verity &>> $seqres.full
_scratch_mount

fsv_orig_file=$SCRATCH_MNT/file
fsv_file=$SCRATCH_MNT/file.fsv

filter_output()
{
	_filter_bash | _filter_scratch
}

verify_data_readable()
{
	local file=$1

	md5sum $file > /dev/null
}


_fsv_scratch_begin_subtest "verity file has correct contents and size"
head -c 100000 /dev/urandom > $fsv_orig_file
cp --reflink $fsv_orig_file $fsv_file
_fsv_enable $fsv_file >> $seqres.full
cmp $fsv_file $fsv_orig_file
_get_filesize $fsv_file
_scratch_cycle_mount
cmp $fsv_file $fsv_orig_file
_get_filesize $fsv_file

_fsv_scratch_begin_subtest "Trying to measure non-verity file fails with ENODATA"
echo foo > $fsv_file
_fsv_measure $fsv_file |& filter_output
verify_data_readable $fsv_file

# Test files <= 1 block in size.  These are a bit of a special case since there
# are no hash blocks; the root hash is calculated directly over the data block.
_fsv_scratch_begin_subtest "verity on small files"
for size in 1 $((FSV_BLOCK_SIZE - 1)) $FSV_BLOCK_SIZE; do
	head -c $size /dev/urandom > $fsv_orig_file
	cp --reflink $fsv_orig_file $fsv_file
	_fsv_enable $fsv_file
	cmp $fsv_orig_file $fsv_file && echo "Files matched"
	rm -f $fsv_file
done

_fsv_scratch_begin_subtest "verity on 100MB file (multiple levels in hash tree)"
head -c 100000000 /dev/urandom > $fsv_orig_file
cp --reflink $fsv_orig_file $fsv_file
_fsv_enable $fsv_file
cmp $fsv_orig_file $fsv_file && echo "Files matched"

_fsv_scratch_begin_subtest "verity on sparse file"
dd if=/dev/zero of=$fsv_orig_file bs=1 count=1 seek=1000000 status=none
cp --reflink $fsv_orig_file $fsv_file
_fsv_enable $fsv_file
cmp $fsv_orig_file $fsv_file && echo "Files matched"

_fsv_scratch_begin_subtest "copy of fsverity file looses fsverity status"
head -c 100000 /dev/urandom > $fsv_orig_file
_fsv_enable $fsv_orig_file
fsv_copy=$SCRATCH_MNT/file.copy
cp --reflink $fsv_orig_file $fsv_copy
cmp $fsv_orig_file $fsv_copy && echo "Files matched"
echo "Trying to write to copy of verity file" >> $seqres.full
echo "test" >> $fsv_copy 2>&1 | _filter_scratch
verify_data_readable $fsv_copy
rm -f $fsv_copy

_fsv_scratch_begin_subtest "enabling verity on copy doesn't affect original"
rm -f $fsv_orig_file $fsv_file
head -c 100000 /dev/urandom > $fsv_orig_file
cp --reflink $fsv_orig_file $fsv_file
_fsv_enable $fsv_file >> $seqres.full
echo "Original file should not have verity:"
_fsv_measure $fsv_orig_file 2>&1 | filter_output
echo "Original file should still be writable:"
echo "test data" >> $fsv_orig_file && echo "Write succeeded"
verify_data_readable $fsv_orig_file

_fsv_scratch_begin_subtest "extend original after copy, then enable verity on copy"
rm -f $fsv_orig_file $fsv_file
head -c 100000 /dev/urandom > $fsv_orig_file
cp --reflink $fsv_orig_file $fsv_file
orig_size=$(_get_filesize $fsv_orig_file)
merkle_size=$((orig_size / FSV_BLOCK_SIZE * 32))
new_size=$((orig_size + merkle_size + 4096))
echo "Extending original file from $orig_size to $new_size bytes" >> $seqres.full
dd if=/dev/urandom of=$fsv_orig_file bs=1 count=$merkle_size seek=$orig_size conv=notrunc status=none
_fsv_enable $fsv_file >> $seqres.full
echo "Verity file should be readable:"
verify_data_readable $fsv_file && echo "Read succeeded"
echo "Verity file should not be writable:"
bash -c "echo 'test' >> $fsv_file" 2>&1 | filter_output

# success, all done
status=0
exit
